import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useContext } from 'react';
import { userContext } from './_app';
import { useRouter } from 'next/router';


export default function Home() {
  const [userLoggedIn, setUserLoggedIn] = useContext(userContext)
  const router = useRouter();

 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Main Page</h1>
       <button onClick={()=> { userLoggedIn ? router.push('/dash') : router.push('/login') }}>Check out</button>
      </main>
    </div>
  )
}
